services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: autotallermanager       
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - autotallermanager_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autotallermanager"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ..                       
      dockerfile: Api/Dockerfile  
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"    
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=autotallermanager;Username=postgres;Password=postgres"  
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: adminexample@admin.com
      PGADMIN_DEFAULT_PASSWORD: Supersegura123!
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  autotallermanager_data:  
